<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Mung Bean',
                'category' => 'Health',
                'image' => 'card-8.png',
                'original_price' => 20.00,
                'sale_price' => 11.00,
                'rating' => 5,
                'description' => 'Fresh organic mung beans grown without any harmful pesticides or chemicals.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg<br><strong>Storage:</strong> Keep in a cool, dry place<br><strong>Shelf Life:</strong> 12 months<br><strong>Origin:</strong> India<br><strong>Certifications:</strong> 100% Organic, Non-GMO<br><strong>Nutritional Facts (per 100g):</strong> Protein 24g, Fiber 16g, Carbs 63g<br><strong>Usage:</strong> Perfect for soups, curries, and sprouting<br><strong>Preparation:</strong> Soak for 6-8 hours before cooking',
            ],
            [
                'name' => 'Brown Hazelnut',
                'category' => 'Nuts',
                'image' => 'Photo__2_-removebg-preview.png',
                'original_price' => 20.00,
                'sale_price' => 12.00,
                'rating' => 5,
                'description' => 'Premium brown hazelnuts sourced from the finest orchards.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Store in airtight container in cool place<br><strong>Shelf Life:</strong> 8 months<br><strong>Origin:</strong> Turkey<br><strong>Variety:</strong> Pontika Grade<br><strong>Nutritional Facts (per 100g):</strong> Protein 14.9g, Fat 60.7g, Fiber 9.7g<br><strong>Health Benefits:</strong> Rich in antioxidants and healthy fats<br><strong>Quality:</strong> Blanched and roasted for best flavor',
            ],
            [
                'name' => 'Eggs',
                'category' => 'Fresh',
                'image' => 'Photo-removebg-preview.png',
                'original_price' => 20.00,
                'sale_price' => 17.00,
                'rating' => 5,
                'description' => 'Fresh farm eggs from free-range chickens with no antibiotics or hormones.',
                'additional_info' => '<strong>Quantity:</strong> 12 eggs per box<br><strong>Size:</strong> Large<br><strong>Storage:</strong> Refrigerate at 2-4°C<br><strong>Shelf Life:</strong> 4 weeks<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> Free-range, Organic<br><strong>Nutritional Facts (per 100g):</strong> Protein 13g, Fat 11g, Cholesterol 372mg<br><strong>Quality Assurance:</strong> No antibiotics, hormones, or additives',
            ],
            [
                'name' => 'Zelco Suji Elaichi Rusk',
                'category' => 'Fresh',
                'image' => 'Photo__1_-removebg-preview.png',
                'original_price' => 20.00,
                'sale_price' => 15.00,
                'rating' => 5,
                'description' => 'Delicious elaichi (cardamom) flavored rusk made with finest ingredients.',
                'additional_info' => '<strong>Package Weight:</strong> 200g<br><strong>Storage:</strong> Keep in cool, dry place in airtight container<br><strong>Shelf Life:</strong> 6 months<br><strong>Origin:</strong> India<br><strong>Flavor:</strong> Elaichi (Cardamom)<br><strong>Nutritional Facts (per 100g):</strong> Energy 370 kcal, Protein 7g, Fat 8g, Carbs 65g<br><strong>Ingredients:</strong> Wheat flour, sugar, ghee, elaichi, salt<br><strong>Perfect For:</strong> Tea time snack, breakfast with milk',
            ],
            [
                'name' => 'White Hazelnut',
                'category' => 'Nuts',
                'image' => 'five-img-two.png',
                'original_price' => 20.00,
                'sale_price' => 12.00,
                'rating' => 5,
                'description' => 'Premium white hazelnuts rich in nutrients and antioxidants.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Store in airtight container<br><strong>Shelf Life:</strong> 8 months<br><strong>Origin:</strong> Turkey<br><strong>Processing:</strong> Blanched, skinless<br><strong>Nutritional Facts (per 100g):</strong> Protein 12g, Fat 63g, Fiber 10g<br><strong>Health Benefits:</strong> Excellent source of vitamin E and minerals<br><strong>Uses:</strong> Snacking, baking, chocolate production',
            ],
            [
                'name' => 'Fresh Corn',
                'category' => 'Fresh',
                'image' => 'five-img-three.png',
                'original_price' => 20.00,
                'sale_price' => 17.00,
                'rating' => 5,
                'description' => 'Sweet and juicy fresh corn harvested at peak ripeness.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg (4-5 ears)<br><strong>Storage:</strong> Refrigerate in plastic bag<br><strong>Shelf Life:</strong> 5-7 days<br><strong>Origin:</strong> Local Farms<br><strong>Harvested:</strong> Peak Ripeness<br><strong>Nutritional Facts (per 100g):</strong> Energy 86 kcal, Protein 3.3g, Carbs 19g, Fiber 2.7g<br><strong>Quality:</strong> Fresh picked within 24 hours<br><strong>Best Use:</strong> Grilling, boiling, or roasting',
            ],
            [
                'name' => 'Organic Almonds',
                'category' => 'Fresh',
                'image' => 'five-img-four.png',
                'original_price' => 20.00,
                'sale_price' => 15.00,
                'rating' => 5,
                'description' => 'Organic California almonds grown using sustainable farming practices.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Keep in airtight container in cool place<br><strong>Shelf Life:</strong> 10 months<br><strong>Origin:</strong> California, USA<br><strong>Certification:</strong> USDA Organic<br><strong>Nutritional Facts (per 100g):</strong> Protein 21.2g, Fat 49.9g, Fiber 12.5g<br><strong>Health Benefits:</strong> Rich in vitamin E, calcium, and magnesium<br><strong>Uses:</strong> Raw snacking, baking, almond butter',
            ],
            [
                'name' => 'Calabrese Broccoli',
                'category' => 'Vegetable',
                'image' => 'card-7.png',
                'original_price' => 20.00,
                'sale_price' => 13.00,
                'rating' => 5,
                'description' => 'Fresh calabrese broccoli rich in vitamins and minerals.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Refrigerate in plastic bag<br><strong>Shelf Life:</strong> 5-7 days<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> Calabrese (Italian Green)<br><strong>Nutritional Facts (per 100g):</strong> Energy 34 kcal, Protein 2.8g, Carbs 7g, Fiber 2.4g<br><strong>Key Nutrients:</strong> Vitamin C, K, Folate<br><strong>Preparation:</strong> Steam, boil, or roast for 8-10 minutes',
            ],
            [
                'name' => 'Fresh Banana Fruites',
                'category' => 'Fresh',
                'image' => 'card-6.png',
                'original_price' => 20.00,
                'sale_price' => 14.00,
                'rating' => 5,
                'description' => 'Fresh ripe bananas with natural sweetness and great nutrition.',
                'additional_info' => '<strong>Quantity:</strong> 1kg (6-7 bananas)<br><strong>Storage:</strong> Room temperature, away from direct sunlight<br><strong>Shelf Life:</strong> 5-7 days<br><strong>Origin:</strong> Tropical Regions<br><strong>Ripeness:</strong> Perfectly ripe and sweet<br><strong>Nutritional Facts (per 100g):</strong> Energy 89 kcal, Protein 1.1g, Carbs 23g, Potassium 358mg<br><strong>Health Benefits:</strong> Great source of potassium and vitamin B6<br><strong>Best For:</strong> Fresh eating, smoothies, baking',
            ],
            [
                'name' => 'White Nuts',
                'category' => 'Millets',
                'image' => 'card-5.png',
                'original_price' => 20.00,
                'sale_price' => 15.00,
                'rating' => 5,
                'description' => 'Premium white nuts packed with essential nutrients.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Store in airtight container<br><strong>Shelf Life:</strong> 8 months<br><strong>Origin:</strong> India<br><strong>Quality:</strong> Hand-selected premium grade<br><strong>Nutritional Facts (per 100g):</strong> Protein 20g, Fat 68g, Fiber 8g<br><strong>Key Minerals:</strong> Magnesium, zinc, iron<br><strong>Health Benefits:</strong> Supports heart health and energy levels',
            ],
            [
                'name' => 'Vegan Red Tomato',
                'category' => 'Vegetable',
                'image' => 'card-4.png',
                'original_price' => 20.00,
                'sale_price' => 17.00,
                'rating' => 5,
                'description' => 'Fresh organic red tomatoes with intense flavor and bright color.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg (5-6 tomatoes)<br><strong>Storage:</strong> Room temperature, stem side down<br><strong>Shelf Life:</strong> 7-10 days<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> Heirloom Red Tomato<br><strong>Nutritional Facts (per 100g):</strong> Energy 18 kcal, Protein 0.9g, Carbs 3.9g, Fiber 1.2g<br><strong>Key Nutrients:</strong> Lycopene, Vitamin C<br><strong>Best Use:</strong> Salads, cooking, sauces, fresh consumption',
            ],
            [
                'name' => 'Organic Spinach',
                'category' => 'Vegetable',
                'image' => 'card-4.png',
                'original_price' => 12.00,
                'sale_price' => 8.50,
                'rating' => 5,
                'description' => 'Crisp organic spinach leaves packed with iron and vitamins.',
                'additional_info' => '<strong>Package Weight:</strong> 250g<br><strong>Storage:</strong> Refrigerate in sealed container<br><strong>Shelf Life:</strong> 5-7 days<br><strong>Origin:</strong> Local Organic Farms<br><strong>Certification:</strong> 100% Organic<br><strong>Nutritional Facts (per 100g):</strong> Energy 23 kcal, Protein 2.7g, Iron 2.7mg, Vitamin A 469µg<br><strong>Health Benefits:</strong> Excellent source of iron, calcium, and antioxidants<br><strong>Uses:</strong> Salads, smoothies, cooking, steaming',
            ],
            [
                'name' => 'Organic Carrots',
                'category' => 'Vegetable',
                'image' => 'card-7.png',
                'original_price' => 15.00,
                'sale_price' => 10.50,
                'rating' => 5,
                'description' => 'Sweet organic carrots bursting with beta-carotene and natural sweetness.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg<br><strong>Storage:</strong> Keep in cool, dry place or refrigerator<br><strong>Shelf Life:</strong> 2-3 weeks<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> Nantes Variety<br><strong>Nutritional Facts (per 100g):</strong> Energy 41 kcal, Beta-carotene 8285µg, Vitamin K 13.2µg, Fiber 2.8g<br><strong>Health Benefits:</strong> Supports eye health and immunity<br><strong>Uses:</strong> Raw snacking, cooking, juicing, roasting',
            ],
            [
                'name' => 'Bell Peppers Mix',
                'category' => 'Vegetable',
                'image' => 'card-6.png',
                'original_price' => 18.00,
                'sale_price' => 12.99,
                'rating' => 5,
                'description' => 'Colorful mix of red, yellow, and green bell peppers with sweet taste.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg (4-5 peppers)<br><strong>Storage:</strong> Refrigerate in vegetable drawer<br><strong>Shelf Life:</strong> 7-10 days<br><strong>Colors:</strong> Red, Yellow, Green Mix<br><strong>Origin:</strong> Local Farms<br><strong>Nutritional Facts (per 100g):</strong> Energy 31 kcal, Vitamin C 80.4mg, Vitamin A 3131IU, Fiber 2.2g<br><strong>Health Benefits:</strong> Rich in vitamin C and antioxidants<br><strong>Uses:</strong> Stir-fry, salads, grilling, stuffing',
            ],
            [
                'name' => 'Organic Cucumber',
                'category' => 'Vegetable',
                'image' => 'card-5.png',
                'original_price' => 10.00,
                'sale_price' => 6.99,
                'rating' => 5,
                'description' => 'Crisp and refreshing organic cucumbers perfect for salads and pickling.',
                'additional_info' => '<strong>Package Weight:</strong> 500g (3-4 cucumbers)<br><strong>Storage:</strong> Keep in cool place or refrigerator<br><strong>Shelf Life:</strong> 5-7 days<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> English Cucumber<br><strong>Nutritional Facts (per 100g):</strong> Energy 16 kcal, Protein 0.7g, Carbs 3.6g, Fiber 0.5g<br><strong>Water Content:</strong> 95.2%<br><strong>Uses:</strong> Salads, pickling, juicing, fresh eating',
            ],
            [
                'name' => 'Free-Range Chicken',
                'category' => 'Fresh',
                'image' => 'card-8.png',
                'original_price' => 35.00,
                'sale_price' => 28.99,
                'rating' => 5,
                'description' => 'Premium quality free-range chicken with no antibiotics or hormones.',
                'additional_info' => '<strong>Package Weight:</strong> 1.5kg whole chicken<br><strong>Storage:</strong> Refrigerate immediately, use within 2 days<br><strong>Shelf Life:</strong> 2 days (refrigerated)<br><strong>Origin:</strong> Local Farms<br><strong>Type:</strong> Free-Range, Organic Fed<br><strong>Nutritional Facts (per 100g):</strong> Protein 25g, Fat 5g, Energy 165 kcal, B vitamins<br><strong>Quality:</strong> No antibiotics, no hormones, natural diet<br><strong>Best Use:</strong> Roasting, grilling, cooking curries',
            ],
            [
                'name' => 'Organic Wheat Flour',
                'category' => 'Health',
                'image' => 'card-6.png',
                'original_price' => 16.00,
                'sale_price' => 11.99,
                'rating' => 5,
                'description' => 'Stone-ground organic whole wheat flour made from premium wheat.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg<br><strong>Storage:</strong> Keep in airtight container in cool, dry place<br><strong>Shelf Life:</strong> 6 months<br><strong>Origin:</strong> India<br><strong>Processing:</strong> Stone-ground, no bleaching<br><strong>Nutritional Facts (per 100g):</strong> Energy 340 kcal, Protein 13.7g, Carbs 72g, Fiber 10.7g<br><strong>Certification:</strong> 100% Organic, Non-GMO<br><strong>Uses:</strong> Bread, roti, pasta, baking',
            ],
            [
                'name' => 'Raw Honey Jar',
                'category' => 'Health',
                'image' => 'card-7.png',
                'original_price' => 25.00,
                'sale_price' => 18.99,
                'rating' => 5,
                'description' => 'Pure raw honey collected from local bees without processing.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Keep in sealed jar at room temperature<br><strong>Shelf Life:</strong> Indefinite<br><strong>Origin:</strong> Local Apiaries<br><strong>Type:</strong> Raw, Unprocessed<br><strong>Composition:</strong> No added sugar or preservatives<br><strong>Health Benefits:</strong> Natural antibacterial, antioxidant properties<br><strong>Uses:</strong> Tea, baking, natural sweetener, wound healing',
            ],
            [
                'name' => 'Organic Rice',
                'category' => 'Health',
                'image' => 'card-8.png',
                'original_price' => 22.00,
                'sale_price' => 15.99,
                'rating' => 5,
                'description' => 'Premium basmati rice grown using organic farming methods.',
                'additional_info' => '<strong>Package Weight:</strong> 2kg<br><strong>Storage:</strong> Keep in airtight container in cool, dry place<br><strong>Shelf Life:</strong> 1 year<br><strong>Origin:</strong> India<br><strong>Type:</strong> Basmati, Long-grain<br><strong>Certification:</strong> 100% Organic<br><strong>Cooking Time:</strong> 15-18 minutes<br><strong>Yield:</strong> 1kg rice yields ~3kg cooked rice<br><strong>Best For:</strong> Biryani, pilaf, risotto, everyday meals',
            ],
            [
                'name' => 'Lentil Mix',
                'category' => 'Health',
                'image' => 'card-5.png',
                'original_price' => 18.00,
                'sale_price' => 12.49,
                'rating' => 5,
                'description' => 'Mixed lentils (red, brown, green) rich in protein and fiber.',
                'additional_info' => '<strong>Package Weight:</strong> 1kg<br><strong>Storage:</strong> Keep in airtight container in cool, dry place<br><strong>Shelf Life:</strong> 12 months<br><strong>Origin:</strong> India<br><strong>Mix Includes:</strong> Red Lentils, Brown Lentils, Green Lentils<br><strong>Nutritional Facts (per 100g):</strong> Protein 25g, Fiber 8g, Carbs 60g<br><strong>Health Benefits:</strong> Excellent plant-based protein source<br><strong>Preparation:</strong> Soak 2-4 hours, cook for 20-40 minutes',
            ],
            [
                'name' => 'Virgin Olive Oil',
                'category' => 'Health',
                'image' => 'card-4.png',
                'original_price' => 32.00,
                'sale_price' => 24.99,
                'rating' => 5,
                'description' => 'Extra virgin olive oil cold-pressed from premium olives.',
                'additional_info' => '<strong>Package Weight:</strong> 500ml<br><strong>Storage:</strong> Keep in cool, dark place away from heat<br><strong>Shelf Life:</strong> 18 months<br><strong>Origin:</strong> Mediterranean<br><strong>Grade:</strong> Extra Virgin, First Cold-Pressed<br><strong>Acidity:</strong> <0.8% free acidity<br><strong>Health Benefits:</strong> Rich in antioxidants, anti-inflammatory properties<br><strong>Uses:</strong> Dressing, cooking, dipping bread, finishing dishes',
            ],
            [
                'name' => 'Organic Tea Set',
                'category' => 'Health',
                'image' => 'card-6.png',
                'original_price' => 20.00,
                'sale_price' => 14.99,
                'rating' => 5,
                'description' => 'Assorted organic herbal tea collection with 5 different flavors.',
                'additional_info' => '<strong>Package Weight:</strong> 50g (10 tea bags per flavor)<br><strong>Storage:</strong> Keep in cool, dry place away from sunlight<br><strong>Shelf Life:</strong> 12 months<br><strong>Origin:</strong> Organic Farms<br><strong>Varieties:</strong> Green Tea, Chamomile, Peppermint, Ginger, Hibiscus<br><strong>Brewing Time:</strong> 3-5 minutes<br><strong>Health Benefits:</strong> No caffeine, natural antioxidants<br><strong>Best Time:</strong> Anytime, especially evening',
            ],
            [
                'name' => 'Chia Seeds',
                'category' => 'Health',
                'image' => 'card-7.png',
                'original_price' => 28.00,
                'sale_price' => 19.99,
                'rating' => 5,
                'description' => 'Premium organic chia seeds packed with omega-3 fatty acids.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Keep in airtight container in cool place<br><strong>Shelf Life:</strong> 18 months<br><strong>Origin:</strong> Mexico<br><strong>Certification:</strong> USDA Organic<br><strong>Nutritional Facts (per 100g):</strong> Omega-3 17.8g, Protein 16.5g, Fiber 27.3g<br><strong>Health Benefits:</strong> Complete protein, excellent source of omega-3s<br><strong>Uses:</strong> Smoothies, pudding, baking, toppings',
            ],
            [
                'name' => 'Flax Seeds',
                'category' => 'Nuts',
                'image' => 'card-8.png',
                'original_price' => 16.00,
                'sale_price' => 10.99,
                'rating' => 5,
                'description' => 'Golden flax seeds rich in lignans and omega-3 fatty acids.',
                'additional_info' => '<strong>Package Weight:</strong> 500g<br><strong>Storage:</strong> Refrigerate after opening to maintain freshness<br><strong>Shelf Life:</strong> 12 months (refrigerated)<br><strong>Origin:</strong> Canada<br><strong>Type:</strong> Golden Flax<br><strong>Nutritional Facts (per 100g):</strong> Omega-3 22.8g, Lignans 643mg, Fiber 27.3g, Protein 18.3g<br><strong>Health Benefits:</strong> Supports digestive and heart health<br><strong>Uses:</strong> Ground in smoothies, oatmeal, baking, salads',
            ],
        ];

        foreach ($products as $product) {
            $product['slug'] = Str::slug($product['name']);
            Product::create($product);
        }
    }
}
